server:
  servlet:
    context-path: /stdng-back
spring:
  jpa:
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
    open-in-view: false
  profiles:
    active: local

---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://192.168.219.10:3306/hong?serverTimezone=UTC&useUnicode=true&charaterEncoding=utf-8&useSSL=false
    username: test
    password: dev!!test
    driver-class-name: com.mysql.jdbc.Driver
  dbcp2:
    validation-query: select 1
    test-while-idle: true
    time-between-eviction-runs-millis: 7200000

---
